name: Run ANT Task and Save Output

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run ANT Task
      run: |
        # Run your ANT task script (adjust if necessary)
        node attention_network_task.js
        
        # Create the 'data' directory if it doesn't exist
        mkdir -p data
        
        # Move all .csv files into the 'data' directory
        mv *.csv data/
      
    - name: List output files
      run: ls -l data/  # List files in the 'data' folder to verify the output

    - name: Commit and push results
      run: |
        # Set up Git configuration
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Stage the 'data/' folder for commit
        git add data/  
        
        # Commit the changes with a message
        git commit -m "Save task output in data folder"
        
        # Push the changes back to the repository
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is needed to push to the repository
